version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/var/www/djangoapp/src
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.14
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/config.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge

  database1_network:
    driver: bridge

volumes:
  database1_volume:
