version: '3'

services:
  djangoapp:
    build: .
    command: gunicorn --chdir hello --bind 0.0.0.0:8000 hello.wsgi:application
    ports:
      - 8000
    volumes:
      - .:/var/www/djangoapp/src
      - static_volume:/var/www/djangoapp/src/static
      - media_volume:/var/www/djangoapp/src/media
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 1337:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/www/djangoapp/src/static
      - media_volume:/var/www/djangoapp/src/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge

  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:
  media_volume:

