version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/var/www/djangoapp/src
    networks:
      - nginx_network

  nginx:
    image: nginx:1.14
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/config.d
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
